# Generated by Django 5.1.7 on 2025-06-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='backdrop',
            field=models.ImageField(blank=True, help_text='Large banner image for film', null=True, upload_to='film_backdrops/'),
        ),
        migrations.AddField(
            model_name='film',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Video thumbnail', null=True, upload_to='film_thumbnails/'),
        ),
        migrations.AddField(
            model_name='film',
            name='video_file',
            field=models.FileField(blank=True, help_text='Main film video file', null=True, upload_to='films/'),
        ),
        migrations.AddField(
            model_name='film',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube or other trailer video URL'),
        ),
    ]
